version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"

  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"

  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    depends_on:
      - elasticsearch
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  monstache:
    restart: always
    image: rwynn/monstache:4.15.1
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticsearch
    environment:
      - MONSTACHE_MONGO_URL=db:27017
      - MONSTACHE_ES_URLS=http://elasticsearch:9200
      - MONSTACHE_DIRECT_READ_NAMESPACES=feeds.adverts, feeds.feeds
    links:
      - elasticsearch
      - db

  importer:
    build: .
    volumes:
      - .:/simpals
    depends_on:
      - db
      - redis
    working_dir: /simpals
    command: python -u import.py

  fetcher:
    build: .
    volumes:
      - .:/simpals
    depends_on:
      - db
      - redis
    working_dir: /simpals
    command: python -u fetcher.py
